stages:
#- init test
- build_test0203

cache:
  key: ${CI_BUILD_REF}
  untracked: true
  paths:
  - node_modules/

before_script:
- export PATH=/home/gitlab_ci_multi_runner/node-v5.10.1-linux-x64/bin:$PATH

#- export PHANTOMJS_CDNURL=https://npm.taobao.org/dist/phantomjs

#Install And Test:
#  stage: init test
#  script:
#  - npm i
#  - ./node_modules/gulp/bin/gulp.js test:ci

Bleeding Edge Test0203:
  stage: build_test0203
  script:
  - npm i
  - bower i -F --allow-root
  - bash deploy_test_aliyun.sh docker-01 test01
  only:
  - master
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
